INSERT INTO maldicao (texto, categoria) VALUES
('Would you rather have the ability to see 10 minutes into the future or 150 years into the future', 'Importado'),
('Would you rather have telekinesis (the ability to move things with your mind) or telepathy (the ability to read minds)', 'Importado'),
('Would you rather team up with Wonder Woman or Captain Marvel', 'Importado'),
('Would you rather be forced to sing along or dance to every single song you hear', 'Importado'),
('Would you rather find true love today or win the lottery next year', 'Importado'),
('Would you rather be in jail for five years or be in a coma for a decade', 'Importado'),
('Would you rather have another 10 years with your partner or a one-night stand with your celebrity crush', 'Importado'),
('Would you rather be chronically under-dressed or overdressed', 'Importado'),
('Would you rather have everyone you know be able to read your thoughts or for everyone you know to have access to your Internet history', 'Importado'),
('Would you rather lose your sight or your memories', 'Importado'),
('Would you rather have universal respect or unlimited power', 'Importado'),
('Would you rather give up air conditioning and heating for the rest of your life or give up the Internet for the rest of your life', 'Importado'),
('Would you rather swim in a pool full of Nutella or a pool full of maple syrup', 'Importado'),
('Would you rather labor under a hot sun or extreme cold', 'Importado'),
('Would you rather stay in during a snow day or build a fort', 'Importado'),
('Would you rather buy 10 things you don’t need every time you go shopping or always forget the one thing that you need when you go to the store', 'Importado'),
('Would you rather never be able to go out during the day or never be able to go out at night', 'Importado'),
('Would you rather have a personal maid or a personal chef', 'Importado'),
('Would you rather have Beyoncé’s talent or Jay-Z‘s business acumen', 'Importado'),
('Would you rather be 11 feet tall or nine inches tall', 'Importado'),
('Would you rather be an extra in an Oscar-winning movie or the lead in a box office bomb', 'Importado'),
('Would you rather vomit on your hero or have your hero vomit on you', 'Importado'),
('Would you rather communicate only in emoji or never be able to text at all ever again', 'Importado'),
('Would you rather be royalty 1,000 years ago or an average person today', 'Importado'),
('Would you rather lounge by the pool or on the beach', 'Importado'),
('Would you rather wear the same socks for a month or the same underwear for a week', 'Importado'),
('Would you rather work an overtime shift with your annoying boss or spend full day with your mother-in-law', 'Importado'),
('Would you rather cuddle a koala or pal around with a panda', 'Importado'),
('Would you rather have a sing-off with Ariana Grande or a dance-off with Rihanna', 'Importado'),
('Would you rather always have B.O. and not know it or always smell B.O. on everyone else', 'Importado'),
('Would you rather watch nothing but Hallmark Christmas movies or nothing but horror movies', 'Importado'),
('Would you rather always be 10 minutes late or always be 20 minutes early', 'Importado'),
('Would you rather spend a week in the forest or a night in a real haunted house', 'Importado'),
('Would you rather find a rat in your kitchen or a roach in your bed', 'Importado'),
('Would you rather have a pause or a rewind button in your life', 'Importado'),
('Would you rather always have a full phone battery or a full gas tank', 'Importado'),
('Would you rather lose all your teeth or lose a day of your life every time you kissed someone', 'Importado'),
('Would you rather drink from a toilet or pee in a litter box', 'Importado'),
('Would you rather be forced to live the same day over and over again for a full year, or take 3 years off the end of your life', 'Importado'),
('Would you rather never eat watermelon ever again or be forced to eat watermelon with every meal', 'Importado'),
('Would you rather get a paper cut every time you turn a page or bite your tongue every time you eat', 'Importado'),
('Would you rather oversleep every day for a week or not get any sleep at all for four days', 'Importado'),
('Would you rather die in 20 years with no regrets or live to 100 with a lot of regrets', 'Importado'),
('Would you rather sip gin with Ryan Reynolds or shoot tequila with Dwayne “The Rock” Johnson', 'Importado'),
('Would you rather get trapped in the middle of a food fight or a water balloon fight', 'Importado'),
('Would you rather walk to work in heels or drive to work in reverse', 'Importado'),
('Would you rather spend a year at war or a year in prison', 'Importado'),
('Would you rather die before or after your partner', 'Importado'),
('Would you rather have a child every year for 20 years or never have any children at all', 'Importado'),
('Would you rather take amazing selfies but look terrible in all other photos or be photogenic everywhere but in your selfies', 'Importado'),
('Would you rather be gassy on a first date or your wedding night', 'Importado'),
('Would you rather Danny DeVito or Danny Trejo play you in a movie', 'Importado'),
('Would you rather be able to take back anything you say or hear any conversation that is about you', 'Importado'),
('Would you rather have skin that changes color based on your emotions or tattoos appear all over your body depicting what you did yesterday', 'Importado'),
('Would you rather hunt and butcher your own meat or never eat meat again', 'Importado'),
('Would you rather lose all of your friends but keep your BFF or lose your BFF but keep the rest of your buds', 'Importado'),
('Would you rather have people spread a terrible lie about you or have people spread terrible but true tales about you', 'Importado'),
('Would you rather walk in on your parents or have them walk in on you', 'Importado'),
('Would you rather be the absolute best at something that no one takes seriously or be average at something well respected', 'Importado'),
('Would you rather have unlimited battery life on all of your devices or have free WiFi wherever you go', 'Importado'),
('Would you rather have Billie Eilish‘s future or Madonna’s legacy', 'Importado'),
('Would you rather have a third nipple or an extra toe', 'Importado'),
('Would you rather solve world hunger or global warming', 'Importado'),
('Would you rather have to wear every shirt inside out or every pair of pants backward', 'Importado'),
('Would you rather live in a treehouse or in a cave', 'Importado'),
('Would you rather win $25,000 or your best friend win $100,000', 'Importado'),
('Would you rather be in history books for something terrible or be forgotten completely after you die', 'Importado'),
('Would you rather travel the world for free for a year or have $50,000 to spend however you please', 'Importado'),
('Would you rather your to only be able to talk to your dog or for your dog to be able to talk to only you—and everyone thinks you’re nuts', 'Importado'),
('Would you rather have a mullet for a year or be bald (no wigs!) for six months', 'Importado'),
('Would you rather go back to the past and meet your loved ones who passed away or go to the future to meet your children or grandchildren to be', 'Importado'),
('Would you rather have Angelina Jolie’s lips or with Jennifer Aniston‘s hair', 'Importado'),
('Would you rather stay the age you are physically forever or stay the way you are now financially forever', 'Importado'),
('Would you rather be in a zombie apocalypse or a robot apocalypse', 'Importado'),
('Would you rather be alone all your life or surrounded by really annoying people', 'Importado'),
('Would you rather give up your cellphone for a month or bathing for a month', 'Importado'),
('Would you rather spend a day cleaning your worst enemy’s house or have your crush spend the day cleaning your house', 'Importado'),
('Would you rather spend a year entirely alone or a year without a home', 'Importado'),
('Would you rather buy all used underwear or all used toothbrushes', 'Importado'),
('Would you rather have a photographic memory or an IQ of 200', 'Importado'),
('Would you rather go on a cruise with your boss or never go on vacation ever again', 'Importado'),
('Would you rather forget your partner’s birthday or your anniversary every year', 'Importado'),
('Would you rather have to wear stilettos to sleep or have to wear slippers everywhere you go', 'Importado'),
('Would you rather change the outcome of the last election or get to decide the outcome of the next election', 'Importado'),
('Would you rather lose the ability to read or lose the ability to speak', 'Importado'),
('Would you rather smooch Chris Pratt, Chris Pine, Chris Evans or Chris Hemsworth', 'Importado'),
('Would you rather be beautiful and stupid or unattractive but a genius', 'Importado'),
('Would you rather have seven fingers on each hand or seven toes on each foot', 'Importado'),
('Would you rather work the job you have now for a year at double your current rate of pay or have one year off with what you are making now', 'Importado'),
('Would you rather be always stuck in traffic but find a perfect parking spot or never hit traffic but always take forever to park', 'Importado'),
('Would you rather have super-sensitive taste buds or super-sensitive hearing', 'Importado'),
('Would you rather ask your ex or a total stranger for a favor', 'Importado'),
('Would you rather go on tour with Elton John or Cher', 'Importado'),
('Would you rather eat only pizza for a year or not eat any pizza for five years', 'Importado'),
('Would you rather never get another present in your life but always pick the perfect present for everyone else or keep getting presents but giving terrible ones to everyone else', 'Importado'),
('Would you rather sleep in a doghouse or let stray dogs sleep in your bed', 'Importado'),
('Would you rather be able to speak any language or be able to communicate with animals', 'Importado'),
('Would you rather have all of your messages and photos leak publicly or never use a cellphone ever again', 'Importado'),
('Would you rather run at 100 mph or fly at 20 mph', 'Importado'),
('Would you rather have Adele‘s voice or Normani’s dance moves', 'Importado'),
('Would you rather have to wear sweatpants everywhere for the rest of your life or never wear sweatpants again', 'Importado'),
('Would you rather have 10,000 spoons when all you need is a knife or always have a knife but never be able to use spoons', 'Importado'),
('Would you rather detect every lie you hear or get away with every lie you tell', 'Importado'),
('Would you rather be the funniest person in a room or the smartest person in a room', 'Importado'),
('Would you rather talk like Yoda or breathe like Darth Vader', 'Importado'),
('Would you rather people knew all the details of your finances or all the details of your love life', 'Importado'),
('Would you rather listen to your least-favorite song on a loop for a year or never listen to any music at all for a year', 'Importado'),
('Would you rather go vegan for a month or only eat meat and dairy for a month', 'Importado'),
('Would you rather clean up someone else’s vomit or someone else’s blood', 'Importado'),
('Would you rather work for Michael Scott or Mr. Burns', 'Importado'),
('Would you rather spend the weekend with pirates or ninjas', 'Importado'),
('Would you rather end every phone call with “I love you” or accidentally call your partner the wrong name during a fight', 'Importado'),
('Would you rather get your paycheck given to you in pennies or never be able to use cash again', 'Importado'),
('Would you rather see Lady Gaga in a movie or see Bradley Cooper in concert', 'Importado'),
('Would you rather win the lottery but have to spend it all in one day or triple your current salary forever', 'Importado'),
('Would you rather live until you are 200 and look your age or look like you’re 22 your whole life, but die at age 65', 'Importado'),
('Would you rather give up cursing forever or give up ice cream for 12 years', 'Importado'),
('Would you rather hear a comforting lie or an uncomfortable truth', 'Importado'),
('Would you rather be locked for a week in a room that’s overly bright or a room that’s totally dark', 'Importado'),
('Would you rather someone see all the photos in your phone or read all your text messages', 'Importado'),
('Would you rather have a South Park-themed wedding or a Family Guy-themed funeral', 'Importado'),
('Would you rather have to hunt and gather all of your food or eat McDonald’s for every meal', 'Importado'),
('Would you rather have fortune or fame', 'Importado'),
('Would you rather celebrate the Fourth of July with Taylor Swift or Christmas with Mariah Carey', 'Importado'),
('Would you rather only be able to listen to one song for the rest of your life or only be able to watch one movie for the rest of your life', 'Importado'),
('Would you rather never use social media again or never watch another movie ever again', 'Importado'),
('Would you rather have police hunting you down for a crime you didn’t commit or a serial killer actually hunting you', 'Importado'),
('Would you rather live a peaceful life in a small cabin in the woods or a drama-filled life in a mansion in a big city', 'Importado'),
('Would you rather find your soulmate or your calling', 'Importado'),
('Would you rather drink sour milk or brush your teeth with soap', 'Importado'),
('Would you rather steal Duchess Meghan or Duchess Kate’s style', 'Importado'),
('Would you rather never get a cold ever again or never be stuck in traffic ever again', 'Importado'),
('Would you rather be tall and average looking or three feet tall but beautiful', 'Importado'),
('Would you rather visit the International Space Station for a week or spend a week in a hotel at the bottom of the ocean', 'Importado'),
('Would you rather confess to cheating on your partner or catch your partner cheating on you', 'Importado'),
('Would you rather have all traffic lights you approach be green or never have to stand in line again', 'Importado'),
('Would you rather share an onscreen kiss with Leonardo DiCaprio or George Clooney', 'Importado'),
('Would you rather never eat Christmas cookies ever again or never eat Halloween candy ever again', 'Importado'),
('Would you rather lose your long-term memory or your short-term memory', 'Importado'),
('Would you rather have a mullet or a perm', 'Importado'),
('Would you rather be stranded in the jungle or in the desert', 'Importado'),
('Would you rather everyone you love forget your birthday or everyone you love sing “Happy Birthday” to you for 24 hours straight', 'Importado'),
('Would you rather be invisible or be able to fly', 'Importado'),
('Would you rather spend every weekend indoors or spend every weekend outdoors', 'Importado'),
('Would you rather party with Jennifer Lopez and Alex Rodriguez or with Kim Kardashian and Kanye West', 'Importado'),
('Would you rather give up wine for a year or drink nothing but wine for a year', 'Importado'),
('Would you rather start a colony on another planet or be the leader of a country on Earth', 'Importado'),
('Would you rather live in a house haunted by friendly ghosts or be a ghost reliving your average day after you die', 'Importado'),
('Would you rather have one wish granted today or 10 wishes granted 20 years from now', 'Importado'),
('Would you rather get hit on by someone 20 years older than you or someone 20 years younger than you', 'Importado'),
('Would you rather fall down in public or pass gas in public', 'Importado'),
('Would you rather only eat raw food or only eat TV dinners', 'Importado'),
('Would you rather run as fast as The Flash or be as strong as Superman', 'Importado'),
('Would you rather never have a wedgie or never have anything stuck in your teeth ever again', 'Importado'),
('Would you rather marry the most attractive person you’ve ever met or the best cook you’ve ever met', 'Importado'),
('Would you rather sing karaoke with Gwen Stefani or with Kelly Clarkson', 'Importado'),
('Would you rather go back to kindergarten with everything you know now or know now everything your future self will learn', 'Importado'),
('Would you rather be able to read minds or predict the future', 'Importado'),
('Would you rather take a pill a day for nutrients and to feel full, but never eat anything again or eat whatever you want but never really feel full', 'Importado'),
('Would you rather be an unknown superhero or an infamous villain', 'Importado'),
('Would you rather always have an annoying song stuck in your head or always have an itch that you can’t reach', 'Importado'),
('Would you rather never be able to keep anyone else’s secrets or have someone tell all of your secrets', 'Importado'),
('Would you rather be Batman or Iron Man', 'Importado'),
('Would you rather be married to someone stunning who doesn’t think you’re attractive or be married to someone ugly who thinks you’re gorgeous', 'Importado'),
('Would you rather have a third ear or a third eye', 'Importado'),
('Would you rather have $1 million now or $5,000 a week for the rest of your life', 'Importado'),
('Would you rather binge-watch Sex And the City or Girls', 'Importado'),
('Would you rather be rich working a job you hate or poor working a job you love', 'Importado'),
('Would you rather wear real fur or fake jewels', 'Importado'),
('Would you rather work a high-paying job that you hate or your dream job with only just enough money for rent, food and utilities', 'Importado'),
('Would you rather wake up naked in a forest five miles from home or in your underwear at work', 'Importado'),
('Would you rather go backstage with your favorite band or be an extra on your favorite TV show', 'Importado'),
('Would you rather never eat your favorite food for the rest of your life or only eat your favorite food', 'Importado'),
('Would you rather be able to erase your own memories or be able to erase someone else’s memories', 'Importado'),
('Would you rather be so afraid of heights that you can’t go to the second floor of a building or be so afraid of the sun that you can only leave the house on rainy days', 'Importado'),
('Would you rather have a rap battle against Nicki Minaj or Lizzo', 'Importado'),
('Would you rather save your best friend’s life if it meant five strangers would die or save five strangers if it meant sacrificing your best friend', 'Importado'),
('Would you rather give up coffee or soda forever', 'Importado'),
('Would you rather find a $100 bill floating in a public toilet or a $20 bill in your own pocket', 'Importado'),
('Would you rather wear nothing but neon orange or neon green for an entire year', 'Importado'),
('Would you rather eat the same thing for every meal for a year or be able to eat whatever you wanted, but only once every three days', 'Importado'),
('Would you rather get drunk off of one sip of alcohol or never get drunk no matter how much booze you imbibe', 'Importado'),
('Would you rather sell all of your possessions or sell one of your organs', 'Importado'),
('Would you rather clean a toilet with your toothbrush or a floor with your tongue', 'Importado'),
('Would you rather be asked the same question over and over again or never be spoken to ever again', 'Importado'),
('Would you rather be reincarnated as a fly or just stop existing when you die', 'Importado'),
('Would you rather be serenaded by Justin Bieber or Justin Timberlake', 'Importado'),
('Would you rather be unable to close any door once it’s open or be unable to open any door once it’s closed', 'Importado'),
('Would you rather throw the best parties but have to clean up the mess by yourself or never go to a party again', 'Importado'),
('Would you rather have a tattoo of the title of the last book you read or the last TV show you watched', 'Importado'),
('Would you rather wear clothes that were always way too big or a couple sizes too small', 'Importado'),
('Would you rather give your parents or your boss access to your browser history', 'Importado'),
('Would you rather only be able to wash your hair twice a year or only be able to check your phone once a day', 'Importado'),
('Would you rather have a tennis lesson from Serena Williams or a soccer lesson from Meghan Rapinoe', 'Importado'),
('Would you rather have a permanent unibrow or no eyebrows at all', 'Importado'),
('Would you rather have aliens be real and covered up by the government or have no extraterrestrial life at all in the universe', 'Importado'),
('Would you rather be caught liking your ex’s Instagram pics or your partner’s ex’s Instagram pics', 'Importado'),
('Would you rather never eat cookies ever again or only ever drink water', 'Importado'),
('Would you rather donate your organs to those who need them or donate your entire body to science', 'Importado'),
('Would you rather be criticized or be ignored', 'Importado'),
('Would you rather work alongside Dwight Schrute or Homer Simpson', 'Importado'),
('Would you rather be punished for a crime you didn’t commit or have someone else take credit for one of your major accomplishments', 'Importado'),
('Would you rather eat an undercooked meal or a burnt meal', 'Importado'),
('Would you rather get a cooking lesson from Gordon Ramsay or Ina Garten', 'Importado'),
('Would you rather have your boss or your parents look through your text messages', 'Importado'),
('Would you rather have your first child when you’re 18 or when you’re 50', 'Importado'),
('Would you rather star in a Star Wars or a Marvel film', 'Importado'),
('Would you rather wear heels to the gym or sneakers to a wedding', 'Importado'),
('Would you rather give up brushing your hair or give us brushing your teeth', 'Importado'),
('Would you rather master every musical instrument or every type of sport', 'Importado'),
('Would you rather always have wet socks or a small rock in your shoe', 'Importado'),
('Would you rather have Celine Dion or Eminem perform the soundtrack to your life', 'Importado'),
('Would you rather be the class clown or the teacher’s pet', 'Importado'),
('Would you rather bathe in the dishwater or wash dishes in your bathwater', 'Importado'),
('Would you rather show up to a job interview with stained pants or pit stains', 'Importado'),
('Would you rather never age physically or never age mentally', 'Importado'),
('Would you rather date someone with bad breath or bad manners', 'Importado'),
('Would you rather never wear makeup ever again or wear a full face of the wrong shades every day', 'Importado'),
('Would you rather read the book or watch the movie', 'Importado'),
('Would you rather have a slumber party with Anna Kendrick or go to a comedy show with Rebel Wilson', 'Importado'),
('Would you rather eat chocolate on pizza or never eat chocolate ever again', 'Importado'),
('Would you rather have X-ray vision of people you find unattractive or everyone else have X-ray vision of you', 'Importado'),
('Would you rather have your own theme park or your own zoo', 'Importado'),
('Would you rather be the star player on a losing team or warm the bench on a championship roster', 'Importado'),
('Would you rather know when you’re going to die or how you’re going to die', 'Importado'),
('Would you rather lose all of your teeth or all of your hair', 'Importado'),
('Would you rather watch nothing but The Office or Friends for the rest of your life', 'Importado'),
('Would you rather lose your keys or your phone', 'Importado'),
('Would you rather live in a home with no electricity or in a home with no running water', 'Importado'),
('Would you rather be rich with no friends or poor and popular', 'Importado'),
('Would you rather look strong and be weak or look weak and be strong', 'Importado'),
('Would you rather have your style critiqued by Anna Wintour or Miranda Priestly', 'Importado'),
('Would you rather wear one or seven colors everyday', 'Importado'),
('Would you rather sneeze nonstop for 15 minutes once every day or sneeze once every three minutes of the day while you’re awake', 'Importado'),
('Would you rather walk barefoot in a public bathroom or through poison ivy', 'Importado'),
('Would you rather have the ability to see 10 years into your own future or six months into the future of the world', 'Importado'),
('Would you rather nobody remember who you are at your 20-year class reunion or have everybody comment on how old you look', 'Importado'),
('Would you rather shoot hoops with LeBron James or toss a football with Tom Brady', 'Importado'),
('Would you rather live through an episode of Orange Is The New Black or Black Mirror', 'Importado'),
('Would you rather only be able to listen to Christmas songs all year round or only be able to watch nothing but horror movies', 'Importado'),
('Would you rather be a genius everyone thinks is an idiot or an idiot everyone thinks is a genius', 'Importado'),
('Would you rather win on Survivor or on The Bachelor or The Bachelorette', 'Importado'),
('Would you rather be beloved by the general public but your family and friends hate you, or be hated by the general public but your family and friends love you', 'Importado'),
('Would you rather be color blind or lose your sense of taste', 'Importado'),
('Would you rather live on a desert island with your celebrity crush or in a mansion with your ex', 'Importado'),
('Would you rather pass gas every time you meet someone new or burp every time you kiss someone', 'Importado'),
('Would you rather have tea with Queen Elizabeth or a beer with Prince Harry', 'Importado'),
('Would you rather give up the Internet or showering for a month', 'Importado'),
('Would you rather get away with a terrible crime but live in fear of someone discovering it or go to prison for three years for a crime you didn’t commit', 'Importado'),
('Saber o dia exato da sua morte mas não como, ou saber como vai morrer mas não quando', 'Original'),
('Poder voar mas só na velocidade de uma caminhada, ou correr na velocidade de um carro mas só no chão', 'Original'),
('Ser invisível sempre que quiser mas não poder usar roupas, ou poder ler mentes mas ouvir todos os pensamentos ao mesmo tempo', 'Original'),
('Ter memória perfeita mas nunca poder esquecer nada, ou esquecer tudo após 24 horas', 'Original'),
('Falar todos os idiomas do mundo menos o português, ou entender todos os animais mas não poder se comunicar com humanos', 'Original'),
('Nunca poder mentir mesmo nas situações mais constrangedoras, ou nunca poder dizer a verdade', 'Original'),
('Saber que seus amigos falam mal de você mas continuarem sendo seus amigos, ou acreditar que te adoram quando na verdade te odeiam', 'Original'),
('Ter um melhor amigo que só está com você pelo seu dinheiro, ou não ter nenhum amigo mas ter todo o dinheiro do mundo', 'Original'),
('Ser muito famoso sem nenhuma privacidade, ou ser completamente desconhecido e nunca ser reconhecido', 'Original'),
('Ter que fazer um discurso em público todo dia, ou nunca poder falar em público', 'Original'),
('Nunca poder dormir mais de 4 horas por noite mas nunca ficar doente, ou dormir 12 horas obrigatoriamente e ficar gripado todo mês', 'Original'),
('Perder o olfato completamente, ou perder o paladar completamente', 'Original'),
('Sempre sentir cheiro ruim de quem está ao seu redor, ou sempre fazer barulhos de digestão em momentos de silêncio', 'Original'),
('Envelhecer 3x mais rápido que o normal, ou envelhecer 3x mais devagar mas com aparência de 12 anos para sempre', 'Original'),
('Nunca mais poder correr, ou nunca mais poder andar devagar', 'Original'),
('Só poder comer pizza pelo resto da vida, ou só poder comer churrasco', 'Original'),
('Nunca mais poder comer doce, ou nunca mais poder comer sal', 'Original'),
('Ter que comer um inseto vivo todo dia, ou nunca poder comer carne de novo', 'Original'),
('Só poder beber água morna pelo resto da vida, ou só poder comer comida sem tempero', 'Original'),
('Comer a mesma refeição favorita todo dia, ou poder comer qualquer coisa menos a sua favorita', 'Original'),
('Nunca mais poder usar redes sociais, ou nunca mais poder usar streaming', 'Original'),
('Perder todo o histórico de fotos do celular, ou perder todos os contatos salvos', 'Original'),
('Só poder usar o celular 30 minutos por dia, ou poder usar à vontade mas sem internet', 'Original'),
('Ter todas as suas mensagens tornadas públicas, ou perder acesso a todas as suas contas para sempre', 'Original'),
('Nunca mais poder ouvir música, ou nunca mais poder assistir a vídeos', 'Original'),
('Ganhar R.000 por mês em um trabalho que você odeia, ou R.000 em um trabalho que ama', 'Original'),
('Ser demitido injustamente sem poder se defender, ou ter que demitir seu melhor amigo', 'Original'),
('Trabalhar 80 horas por semana sem férias, ou trabalhar 20 horas ganhando só o suficiente para sobreviver', 'Original'),
('Perder todas as suas economias de uma vez, ou gastar 30% de tudo que ganhar com coisas inúteis para sempre', 'Original'),
('Ter todo o dinheiro do mundo mas nunca poder gastar nada, ou ter exatamente o suficiente mas gastar como quiser', 'Original'),
('Viajar para qualquer lugar do mundo sem poder escolher o destino, ou nunca viajar mas conhecer tudo pelos livros', 'Original'),
('Ficar preso em uma ilha deserta por um ano com uma pessoa que você odeia, ou em casa sozinho por dois anos', 'Original'),
('Perder a bagagem com documentos em viagem internacional, ou voltar de férias e descobrir que perdeu o emprego', 'Original'),
('Ter medo de avião e precisar viajar toda semana, ou ter medo de altura e morar no 30 andar', 'Original'),
('Viver em outro país sem falar o idioma, ou ficar no Brasil sem nunca poder sair', 'Original'),
('Chamar o professor de mãe na frente da turma, ou soltar um pum alto em uma reunião importante', 'Original'),
('Enviar uma mensagem íntima para o contato errado, ou receber uma mensagem íntima de alguém inesperado', 'Original'),
('Aparecer de pijama em uma formatura, ou ir a uma festa fantasiado sem precisar', 'Original'),
('Esquecer o nome de alguém que você vê todo dia, ou lembrar de todos os nomes mas sempre chamar pelo errado', 'Original'),
('Cair de cara no chão em público, ou gaguejar em um discurso importante ao vivo', 'Original'),
('Poder parar o tempo mas envelhecer normalmente na pausa, ou poder voltar no tempo mas não poder mudar nada', 'Original'),
('Ser rico mas sem amigos, ou ser pobre mas com os melhores amigos do mundo', 'Original'),
('Ter a força de um super-herói mas sem controle, ou ter a velocidade de um super-herói mas só no modo lento', 'Original'),
('Ser imortal e ver todos morrerem ao seu redor, ou ter uma vida curta mas repleta de felicidade', 'Original'),
('Saber tudo sobre ciência mas não entender nada de arte, ou entender tudo de arte mas não saber nada de ciência', 'Original'),
('Poder falar com animais mas todos te odiarem, ou não poder falar com animais mas todos te adorarem', 'Original'),
('Ser perseguido por uma galinha furiosa toda vez que sair de casa, ou ter que tocar em um caracol todo dia', 'Original'),
('Ter um leão manso com você que aterroriza os vizinhos, ou um cachorro que late 24 horas sem parar', 'Original'),
('Acordar uma vez por semana transformado em um animal aleatório, ou nunca mais poder ver animais', 'Original'),
('Ter que carregar um frango vivo na mochila para todo lugar, ou ter que viver com um peixe enorme na banheira', 'Original'),
('Saber todos os segredos da sua família, ou que sua família saiba todos os seus segredos', 'Original'),
('Que seus pais leiam todas as suas mensagens, ou que seu chefe saiba tudo que você faz nas horas vagas', 'Original'),
('Passar o Natal sozinho todo ano, ou passar todas as festas de aniversário com quem você não suporta', 'Original'),
('Decepcionar quem você mais ama uma vez para sempre, ou decepcionar um desconhecido toda semana', 'Original'),
('Perder contato com todos os amigos por um ano, ou ver seus amigos todo dia mas nunca ter uma conversa profunda', 'Original');
