SET FOREIGN_KEY_CHECKS=0;
DELETE FROM maldicao WHERE id IN (1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,73,74,75,76,77,78,79,80,81,83,84,85,87,88,89,90,91,92,94,95,96,97,98,99,100,101,103,104,106,107,109,111,112,113,114,115,116,117,118,119,120,121,122,123,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,157,158,159,161,162,164,165,166,168,169,170,171,172,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,195,196,197,198,199,200,201,202,203,204,205,206,208,209,210,211,213,214,215,216,217,218,219,220,221,222,223,224,225,226,228,229,230,231,232,233,234,235,236,237,240,241,243,244,245,246,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304);
INSERT INTO maldicao (texto, categoria) VALUES
('Would you rather have the ability to see 10 minutes into the future', 'Importado'),
('150 years into the future', 'Importado'),
('Would you rather have telekinesis (the ability to move things with your mind)', 'Importado'),
('telepathy (the ability to read minds)', 'Importado'),
('Would you rather team up with Wonder Woman', 'Importado'),
('Captain Marvel', 'Importado'),
('Would you rather be forced to sing along', 'Importado'),
('dance to every single song you hear', 'Importado'),
('Would you rather find true love today', 'Importado'),
('win the lottery next year', 'Importado'),
('Would you rather be in jail for five years', 'Importado'),
('be in a coma for a decade', 'Importado'),
('Would you rather have another 10 years with your partner', 'Importado'),
('a one-night stand with your celebrity crush', 'Importado'),
('Would you rather be chronically under-dressed', 'Importado'),
('overdressed', 'Importado'),
('Would you rather have everyone you know be able to read your thoughts', 'Importado'),
('for everyone you know to have access to your Internet history', 'Importado'),
('Would you rather lose your sight', 'Importado'),
('your memories', 'Importado'),
('Would you rather have universal respect', 'Importado'),
('unlimited power', 'Importado'),
('Would you rather swim in a pool full of Nutella', 'Importado'),
('a pool full of maple syrup', 'Importado'),
('Would you rather labor under a hot sun', 'Importado'),
('extreme cold', 'Importado'),
('Would you rather stay in during a snow day', 'Importado'),
('build a fort', 'Importado'),
('Would you rather buy 10 things you don’t need every time you go shopping', 'Importado'),
('always forget the one thing that you need when you go to the store', 'Importado'),
('Would you rather never be able to go out during the day', 'Importado'),
('never be able to go out at night', 'Importado'),
('Would you rather have a personal maid', 'Importado'),
('a personal chef', 'Importado'),
('Would you rather be 11 feet tall', 'Importado'),
('nine inches tall', 'Importado'),
('Would you rather be an extra in an Oscar-winning movie', 'Importado'),
('the lead in a box office bomb', 'Importado'),
('Would you rather vomit on your hero', 'Importado'),
('have your hero vomit on you', 'Importado'),
('Would you rather communicate only in emoji', 'Importado'),
('never be able to text at all ever again', 'Importado'),
('Would you rather be royalty 1,000 years ago', 'Importado'),
('an average person today', 'Importado'),
('Would you rather lounge by the pool', 'Importado'),
('on the beach', 'Importado'),
('Would you rather wear the same socks for a month', 'Importado'),
('the same underwear for a week', 'Importado'),
('Would you rather work an overtime shift with your annoying boss', 'Importado'),
('spend full day with your mother-in-law', 'Importado'),
('Would you rather cuddle a koala', 'Importado'),
('pal around with a panda', 'Importado'),
('Would you rather have a sing-off with Ariana Grande', 'Importado'),
('a dance-off with Rihanna', 'Importado'),
('Would you rather always have B.O. and not know it', 'Importado'),
('always smell B.O. on everyone else', 'Importado'),
('Would you rather always be 10 minutes late', 'Importado'),
('always be 20 minutes early', 'Importado'),
('Would you rather spend a week in the forest', 'Importado'),
('a night in a real haunted house', 'Importado'),
('Would you rather find a rat in your kitchen', 'Importado'),
('a roach in your bed', 'Importado'),
('Would you rather have a pause', 'Importado'),
('a rewind button in your life', 'Importado'),
('Would you rather always have a full phone battery', 'Importado'),
('a full gas tank', 'Importado'),
('Would you rather lose all your teeth', 'Importado'),
('lose a day of your life every time you kissed someone', 'Importado'),
('Would you rather drink from a toilet', 'Importado'),
('pee in a litter box', 'Importado'),
('Would you rather be forced to live the same day over and over again for a full year,', 'Importado'),
('take 3 years off the end of your life', 'Importado'),
('Would you rather never eat watermelon ever again', 'Importado'),
('be forced to eat watermelon with every meal', 'Importado'),
('Would you rather get a paper cut every time you turn a page', 'Importado'),
('bite your tongue every time you eat', 'Importado'),
('Would you rather oversleep every day for a week', 'Importado'),
('not get any sleep at all for four days', 'Importado'),
('Would you rather die in 20 years with no regrets', 'Importado'),
('live to 100 with a lot of regrets', 'Importado'),
('Would you rather sip gin with Ryan Reynolds', 'Importado'),
('shoot tequila with Dwayne “The Rock” Johnson', 'Importado'),
('Would you rather get trapped in the middle of a food fight', 'Importado'),
('a water balloon fight', 'Importado'),
('Would you rather walk to work in heels', 'Importado'),
('drive to work in reverse', 'Importado'),
('Would you rather spend a year at war', 'Importado'),
('a year in prison', 'Importado'),
('Would you rather die before', 'Importado'),
('after your partner', 'Importado'),
('Would you rather have a child every year for 20 years', 'Importado'),
('never have any children at all', 'Importado'),
('Would you rather take amazing selfies but look terrible in all other photos', 'Importado'),
('be photogenic everywhere but in your selfies', 'Importado'),
('Would you rather Danny DeVito', 'Importado'),
('Danny Trejo play you in a movie', 'Importado'),
('Would you rather be able to take back anything you say', 'Importado'),
('hear any conversation that is about you', 'Importado'),
('Would you rather have skin that changes color based on your emotions', 'Importado'),
('tattoos appear all over your body depicting what you did yesterday', 'Importado'),
('Would you rather hunt and butcher your own meat', 'Importado'),
('never eat meat again', 'Importado'),
('Would you rather lose all of your friends but keep your BFF', 'Importado'),
('lose your BFF but keep the rest of your buds', 'Importado'),
('Would you rather have people spread a terrible lie about you', 'Importado'),
('have people spread terrible but true tales about you', 'Importado'),
('Would you rather walk in on your parents', 'Importado'),
('have them walk in on you', 'Importado'),
('Would you rather be the absolute best at something that no one takes seriously', 'Importado'),
('be average at something well respected', 'Importado'),
('Would you rather have unlimited battery life on all of your devices', 'Importado'),
('have free WiFi wherever you go', 'Importado'),
('Would you rather have Billie Eilish‘s future', 'Importado'),
('Madonna’s legacy', 'Importado'),
('Would you rather have a third nipple', 'Importado'),
('an extra toe', 'Importado'),
('Would you rather solve world hunger', 'Importado'),
('global warming', 'Importado'),
('Would you rather have to wear every shirt inside out', 'Importado'),
('every pair of pants backward', 'Importado'),
('Would you rather live in a treehouse', 'Importado'),
('in a cave', 'Importado'),
('Would you rather win $25,000', 'Importado'),
('your best friend win $100,000', 'Importado'),
('Would you rather be in history books for something terrible', 'Importado'),
('be forgotten completely after you die', 'Importado'),
('Would you rather travel the world for free for a year', 'Importado'),
('have $50,000 to spend however you please', 'Importado'),
('Would you rather your to only be able to talk to your dog', 'Importado'),
('for your dog to be able to talk to only you—and everyone thinks you’re nuts', 'Importado'),
('Would you rather have a mullet for a year', 'Importado'),
('be bald (no wigs!) for six months', 'Importado'),
('Would you rather go back to the past and meet your loved ones who passed away', 'Importado'),
('go to the future to meet your children or grandchildren to be', 'Importado'),
('Would you rather stay the age you are physically forever', 'Importado'),
('stay the way you are now financially forever', 'Importado'),
('Would you rather be in a zombie apocalypse', 'Importado'),
('a robot apocalypse', 'Importado'),
('Would you rather be alone all your life', 'Importado'),
('surrounded by really annoying people', 'Importado'),
('Would you rather give up your cellphone for a month', 'Importado'),
('bathing for a month', 'Importado'),
('Would you rather spend a day cleaning your worst enemy’s house', 'Importado'),
('have your crush spend the day cleaning your house', 'Importado'),
('Would you rather spend a year entirely alone', 'Importado'),
('a year without a home', 'Importado'),
('Would you rather buy all used underwear', 'Importado'),
('all used toothbrushes', 'Importado'),
('Would you rather have a photographic memory', 'Importado'),
('an IQ of 200', 'Importado'),
('Would you rather go on a cruise with your boss', 'Importado'),
('never go on vacation ever again', 'Importado'),
('Would you rather have to wear stilettos to sleep', 'Importado'),
('have to wear slippers everywhere you go', 'Importado'),
('Would you rather change the outcome of the last election', 'Importado'),
('get to decide the outcome of the next election', 'Importado'),
('Would you rather lose the ability to read', 'Importado'),
('lose the ability to speak', 'Importado'),
('Would you rather be beautiful and stupid', 'Importado'),
('unattractive but a genius', 'Importado'),
('Would you rather have seven fingers on each hand', 'Importado'),
('seven toes on each foot', 'Importado'),
('Would you rather work the job you have now for a year at double your current rate of pay', 'Importado'),
('have one year off with what you are making now', 'Importado'),
('Would you rather be always stuck in traffic but find a perfect parking spot', 'Importado'),
('never hit traffic but always take forever to park', 'Importado'),
('Would you rather have super-sensitive taste buds', 'Importado'),
('super-sensitive hearing', 'Importado'),
('Would you rather ask your ex', 'Importado'),
('a total stranger for a favor', 'Importado'),
('Would you rather eat only pizza for a year', 'Importado'),
('not eat any pizza for five years', 'Importado'),
('Would you rather never get another present in your life but always pick the perfect present for everyone else', 'Importado'),
('keep getting presents but giving terrible ones to everyone else', 'Importado'),
('Would you rather sleep in a doghouse', 'Importado'),
('let stray dogs sleep in your bed', 'Importado'),
('Would you rather be able to speak any language', 'Importado'),
('be able to communicate with animals', 'Importado'),
('Would you rather have all of your messages and photos leak publicly', 'Importado'),
('never use a cellphone ever again', 'Importado'),
('Would you rather run at 100 mph', 'Importado'),
('fly at 20 mph', 'Importado'),
('Would you rather have Adele‘s voice', 'Importado'),
('Normani’s dance moves', 'Importado'),
('Would you rather have to wear sweatpants everywhere for the rest of your life', 'Importado'),
('never wear sweatpants again', 'Importado'),
('Would you rather detect every lie you hear', 'Importado'),
('get away with every lie you tell', 'Importado'),
('Would you rather be the funniest person in a room', 'Importado'),
('the smartest person in a room', 'Importado'),
('Would you rather people knew all the details of your finances', 'Importado'),
('all the details of your love life', 'Importado'),
('Would you rather listen to your least-favorite song on a loop for a year', 'Importado'),
('never listen to any music at all for a year', 'Importado'),
('Would you rather clean up someone else’s vomit', 'Importado'),
('someone else’s blood', 'Importado'),
('Would you rather spend the weekend with pirates', 'Importado'),
('ninjas', 'Importado'),
('Would you rather end every phone call with “I love you”', 'Importado'),
('accidentally call your partner the wrong name during a fight', 'Importado'),
('Would you rather get your paycheck given to you in pennies', 'Importado'),
('never be able to use cash again', 'Importado'),
('Would you rather see Lady Gaga in a movie', 'Importado'),
('see Bradley Cooper in concert', 'Importado'),
('Would you rather win the lottery but have to spend it all in one day', 'Importado'),
('triple your current salary forever', 'Importado'),
('Would you rather live until you are 200 and look your age', 'Importado'),
('look like you’re 22 your whole life, but die at age 65', 'Importado'),
('Would you rather give up cursing forever', 'Importado'),
('give up ice cream for 12 years', 'Importado'),
('Would you rather hear a comforting lie', 'Importado'),
('an uncomfortable truth', 'Importado'),
('Would you rather be locked for a week in a room that’s overly bright', 'Importado'),
('a room that’s totally dark', 'Importado'),
('Would you rather someone see all the photos in your phone', 'Importado'),
('read all your text messages', 'Importado'),
('Would you rather have a South Park-themed wedding', 'Importado'),
('a Family Guy-themed funeral', 'Importado'),
('Would you rather have to hunt and gather all of your food', 'Importado'),
('eat McDonald’s for every meal', 'Importado'),
('Would you rather have fortune', 'Importado'),
('fame', 'Importado'),
('Would you rather only be able to listen to one song for the rest of your life', 'Importado'),
('only be able to watch one movie for the rest of your life', 'Importado'),
('Would you rather never use social media again', 'Importado'),
('never watch another movie ever again', 'Importado'),
('Would you rather have police hunting you down for a crime you didn’t commit', 'Importado'),
('a serial killer actually hunting you', 'Importado'),
('Would you rather live a peaceful life in a small cabin in the woods', 'Importado'),
('a drama-filled life in a mansion in a big city', 'Importado'),
('Would you rather find your soulmate', 'Importado'),
('your calling', 'Importado'),
('Would you rather drink sour milk', 'Importado'),
('brush your teeth with soap', 'Importado'),
('Would you rather steal Duchess Meghan', 'Importado'),
('Duchess Kate’s style', 'Importado'),
('Would you rather never get a cold ever again', 'Importado'),
('never be stuck in traffic ever again', 'Importado'),
('Would you rather be tall and average looking', 'Importado'),
('three feet tall but beautiful', 'Importado'),
('Would you rather visit the International Space Station for a week', 'Importado'),
('spend a week in a hotel at the bottom of the ocean', 'Importado'),
('Would you rather confess to cheating on your partner', 'Importado'),
('catch your partner cheating on you', 'Importado'),
('Would you rather have all traffic lights you approach be green', 'Importado'),
('never have to stand in line again', 'Importado'),
('Would you rather share an onscreen kiss with Leonardo DiCaprio', 'Importado'),
('George Clooney', 'Importado'),
('Would you rather never eat Christmas cookies ever again', 'Importado'),
('never eat Halloween candy ever again', 'Importado'),
('Would you rather lose your long-term memory', 'Importado'),
('your short-term memory', 'Importado'),
('Would you rather have a mullet', 'Importado'),
('a perm', 'Importado'),
('Would you rather be stranded in the jungle', 'Importado'),
('in the desert', 'Importado'),
('Would you rather everyone you love forget your birthday', 'Importado'),
('everyone you love sing “Happy Birthday” to you for 24 hours straight', 'Importado'),
('Would you rather be invisible', 'Importado'),
('be able to fly', 'Importado'),
('Would you rather spend every weekend indoors', 'Importado'),
('spend every weekend outdoors', 'Importado'),
('Would you rather party with Jennifer Lopez and Alex Rodriguez', 'Importado'),
('with Kim Kardashian and Kanye West', 'Importado'),
('Would you rather give up wine for a year', 'Importado'),
('drink nothing but wine for a year', 'Importado'),
('Would you rather start a colony on another planet', 'Importado'),
('be the leader of a country on Earth', 'Importado'),
('Would you rather live in a house haunted by friendly ghosts', 'Importado'),
('be a ghost reliving your average day after you die', 'Importado'),
('Would you rather have one wish granted today', 'Importado'),
('10 wishes granted 20 years from now', 'Importado'),
('Would you rather get hit on by someone 20 years older than you', 'Importado'),
('someone 20 years younger than you', 'Importado'),
('Would you rather fall down in public', 'Importado'),
('pass gas in public', 'Importado'),
('Would you rather only eat raw food', 'Importado'),
('only eat TV dinners', 'Importado'),
('Would you rather run as fast as The Flash', 'Importado'),
('be as strong as Superman', 'Importado'),
('Would you rather never have a wedgie', 'Importado'),
('never have anything stuck in your teeth ever again', 'Importado'),
('Would you rather marry the most attractive person you’ve ever met', 'Importado'),
('the best cook you’ve ever met', 'Importado'),
('Would you rather go back to kindergarten with everything you know now', 'Importado'),
('know now everything your future self will learn', 'Importado'),
('Would you rather be able to read minds', 'Importado'),
('predict the future', 'Importado'),
('Would you rather take a pill a day for nutrients and to feel full, but never eat anything again', 'Importado'),
('eat whatever you want but never really feel full', 'Importado'),
('Would you rather always have an annoying song stuck in your head', 'Importado'),
('always have an itch that you can’t reach', 'Importado'),
('Would you rather never be able to keep anyone else’s secrets', 'Importado'),
('have someone tell all of your secrets', 'Importado'),
('Would you rather be married to someone stunning who doesn’t think you’re attractive', 'Importado'),
('be married to someone ugly who thinks you’re gorgeous', 'Importado'),
('Would you rather have a third ear', 'Importado'),
('a third eye', 'Importado'),
('Would you rather have $1 million now', 'Importado'),
('$5,000 a week for the rest of your life', 'Importado'),
('Would you rather be rich working a job you hate', 'Importado'),
('poor working a job you love', 'Importado'),
('Would you rather wear real fur', 'Importado'),
('fake jewels', 'Importado'),
('Would you rather work a high-paying job that you hate', 'Importado'),
('your dream job with only just enough money for rent, food and utilities', 'Importado'),
('Would you rather wake up naked in a forest five miles from home', 'Importado'),
('in your underwear at work', 'Importado'),
('Would you rather go backstage with your favorite band', 'Importado'),
('be an extra on your favorite TV show', 'Importado'),
('Would you rather be able to erase your own memories', 'Importado'),
('be able to erase someone else’s memories', 'Importado'),
('Would you rather be so afraid of heights that you can’t go to the second floor of a building', 'Importado'),
('be so afraid of the sun that you can only leave the house on rainy days', 'Importado'),
('Would you rather have a rap battle against Nicki Minaj', 'Importado'),
('Lizzo', 'Importado'),
('Would you rather save your best friend’s life if it meant five strangers would die', 'Importado'),
('save five strangers if it meant sacrificing your best friend', 'Importado'),
('Would you rather give up coffee', 'Importado'),
('soda forever', 'Importado'),
('Would you rather find a $100 bill floating in a public toilet', 'Importado'),
('a $20 bill in your own pocket', 'Importado'),
('Would you rather wear nothing but neon orange', 'Importado'),
('neon green for an entire year', 'Importado'),
('Would you rather eat the same thing for every meal for a year', 'Importado'),
('be able to eat whatever you wanted, but only once every three days', 'Importado'),
('Would you rather get drunk off of one sip of alcohol', 'Importado'),
('never get drunk no matter how much booze you imbibe', 'Importado'),
('Would you rather sell all of your possessions', 'Importado'),
('sell one of your organs', 'Importado'),
('Would you rather clean a toilet with your toothbrush', 'Importado'),
('a floor with your tongue', 'Importado'),
('Would you rather be asked the same question over and over again', 'Importado'),
('never be spoken to ever again', 'Importado'),
('Would you rather be reincarnated as a fly', 'Importado'),
('just stop existing when you die', 'Importado'),
('Would you rather be serenaded by Justin Bieber', 'Importado'),
('Justin Timberlake', 'Importado'),
('Would you rather be unable to close any door once it’s open', 'Importado'),
('be unable to open any door once it’s closed', 'Importado'),
('Would you rather throw the best parties but have to clean up the mess by yourself', 'Importado'),
('never go to a party again', 'Importado'),
('Would you rather have a tattoo of the title of the last book you read', 'Importado'),
('the last TV show you watched', 'Importado'),
('Would you rather wear clothes that were always way too big', 'Importado'),
('a couple sizes too small', 'Importado'),
('Would you rather give your parents', 'Importado'),
('your boss access to your browser history', 'Importado'),
('Would you rather only be able to wash your hair twice a year', 'Importado'),
('only be able to check your phone once a day', 'Importado'),
('Would you rather have a permanent unibrow', 'Importado'),
('no eyebrows at all', 'Importado'),
('Would you rather have aliens be real and covered up by the government', 'Importado'),
('have no extraterrestrial life at all in the universe', 'Importado'),
('Would you rather be caught liking your ex’s Instagram pics', 'Importado'),
('your partner’s ex’s Instagram pics', 'Importado'),
('Would you rather never eat cookies ever again', 'Importado'),
('only ever drink water', 'Importado'),
('Would you rather donate your organs to those who need them', 'Importado'),
('donate your entire body to science', 'Importado'),
('Would you rather be criticized', 'Importado'),
('be ignored', 'Importado'),
('Would you rather work alongside Dwight Schrute', 'Importado'),
('Homer Simpson', 'Importado'),
('Would you rather be punished for a crime you didn’t commit', 'Importado'),
('have someone else take credit for one of your major accomplishments', 'Importado'),
('Would you rather eat an undercooked meal', 'Importado'),
('a burnt meal', 'Importado'),
('Would you rather get a cooking lesson from Gordon Ramsay', 'Importado'),
('Ina Garten', 'Importado'),
('Would you rather have your boss', 'Importado'),
('your parents look through your text messages', 'Importado'),
('Would you rather have your first child when you’re 18', 'Importado'),
('when you’re 50', 'Importado'),
('Would you rather wear heels to the gym', 'Importado'),
('sneakers to a wedding', 'Importado'),
('Would you rather give up brushing your hair', 'Importado'),
('give us brushing your teeth', 'Importado'),
('Would you rather master every musical instrument', 'Importado'),
('every type of sport', 'Importado'),
('Would you rather always have wet socks', 'Importado'),
('a small rock in your shoe', 'Importado'),
('Would you rather be the class clown', 'Importado'),
('the teacher’s pet', 'Importado'),
('Would you rather bathe in the dishwater', 'Importado'),
('wash dishes in your bathwater', 'Importado'),
('Would you rather show up to a job interview with stained pants', 'Importado'),
('pit stains', 'Importado'),
('Would you rather never age physically', 'Importado'),
('never age mentally', 'Importado'),
('Would you rather date someone with bad breath', 'Importado'),
('bad manners', 'Importado'),
('Would you rather never wear makeup ever again', 'Importado'),
('wear a full face of the wrong shades every day', 'Importado'),
('Would you rather read the book', 'Importado'),
('watch the movie', 'Importado'),
('Would you rather have a slumber party with Anna Kendrick', 'Importado'),
('go to a comedy show with Rebel Wilson', 'Importado'),
('Would you rather eat chocolate on pizza', 'Importado'),
('never eat chocolate ever again', 'Importado'),
('Would you rather have X-ray vision of people you find unattractive', 'Importado'),
('everyone else have X-ray vision of you', 'Importado'),
('Would you rather have your own theme park', 'Importado'),
('your own zoo', 'Importado'),
('Would you rather be the star player on a losing team', 'Importado'),
('warm the bench on a championship roster', 'Importado'),
('Would you rather know when you’re going to die', 'Importado'),
('how you’re going to die', 'Importado'),
('Would you rather lose all of your teeth', 'Importado'),
('all of your hair', 'Importado'),
('Would you rather lose your keys', 'Importado'),
('your phone', 'Importado'),
('Would you rather live in a home with no electricity', 'Importado'),
('in a home with no running water', 'Importado'),
('Would you rather be rich with no friends', 'Importado'),
('poor and popular', 'Importado'),
('Would you rather look strong and be weak', 'Importado'),
('look weak and be strong', 'Importado'),
('Would you rather have your style critiqued by Anna Wintour', 'Importado'),
('Miranda Priestly', 'Importado'),
('Would you rather wear one', 'Importado'),
('seven colors everyday', 'Importado'),
('Would you rather sneeze nonstop for 15 minutes once every day', 'Importado'),
('sneeze once every three minutes of the day while you’re awake', 'Importado'),
('Would you rather walk barefoot in a public bathroom', 'Importado'),
('through poison ivy', 'Importado'),
('Would you rather have the ability to see 10 years into your own future', 'Importado'),
('six months into the future of the world', 'Importado'),
('Would you rather nobody remember who you are at your 20-year class reunion', 'Importado'),
('have everybody comment on how old you look', 'Importado'),
('Would you rather only be able to listen to Christmas songs all year round', 'Importado'),
('only be able to watch nothing but horror movies', 'Importado'),
('Would you rather be a genius everyone thinks is an idiot', 'Importado'),
('an idiot everyone thinks is a genius', 'Importado'),
('Would you rather be beloved by the general public but your family and friends hate you,', 'Importado'),
('be hated by the general public but your family and friends love you', 'Importado'),
('Would you rather be color blind', 'Importado'),
('lose your sense of taste', 'Importado'),
('Would you rather live on a desert island with your celebrity crush', 'Importado'),
('in a mansion with your ex', 'Importado'),
('Would you rather pass gas every time you meet someone new', 'Importado'),
('burp every time you kiss someone', 'Importado'),
('Would you rather give up the Internet', 'Importado'),
('showering for a month', 'Importado'),
('Would you rather get away with a terrible crime but live in fear of someone discovering it', 'Importado'),
('go to prison for three years for a crime you didn’t commit', 'Importado'),
('Saber o dia exato da sua morte mas não como', 'Original'),
('saber como vai morrer mas não quando', 'Original'),
('Poder voar mas só na velocidade de uma caminhada', 'Original'),
('correr na velocidade de um carro mas só no chão', 'Original'),
('Ser invisível sempre que quiser mas não poder usar roupas', 'Original'),
('poder ler mentes mas ouvir todos os pensamentos ao mesmo tempo', 'Original'),
('Ter memória perfeita mas nunca poder esquecer nada', 'Original'),
('esquecer tudo após 24 horas', 'Original'),
('Falar todos os idiomas do mundo menos o português', 'Original'),
('entender todos os animais mas não poder se comunicar com humanos', 'Original'),
('Nunca poder mentir mesmo nas situações mais constrangedoras', 'Original'),
('nunca poder dizer a verdade', 'Original'),
('Saber que seus amigos falam mal de você mas continuarem sendo seus amigos', 'Original'),
('acreditar que te adoram quando na verdade te odeiam', 'Original'),
('Ter um melhor amigo que só está com você pelo seu dinheiro', 'Original'),
('não ter nenhum amigo mas ter todo o dinheiro do mundo', 'Original'),
('Ser muito famoso sem nenhuma privacidade', 'Original'),
('ser completamente desconhecido e nunca ser reconhecido', 'Original'),
('Ter que fazer um discurso em público todo dia', 'Original'),
('nunca poder falar em público', 'Original'),
('Nunca poder dormir mais de 4 horas por noite mas nunca ficar doente', 'Original'),
('dormir 12 horas obrigatoriamente e ficar gripado todo mês', 'Original'),
('Perder o olfato completamente', 'Original'),
('perder o paladar completamente', 'Original'),
('Sempre sentir cheiro ruim de quem está ao seu redor', 'Original'),
('sempre fazer barulhos de digestão em momentos de silêncio', 'Original'),
('Envelhecer 3x mais rápido que o normal', 'Original'),
('envelhecer 3x mais devagar mas com aparência de 12 anos para sempre', 'Original'),
('Nunca mais poder correr', 'Original'),
('nunca mais poder andar devagar', 'Original'),
('Só poder comer pizza pelo resto da vida', 'Original'),
('só poder comer churrasco', 'Original'),
('Nunca mais poder comer doce', 'Original'),
('nunca mais poder comer sal', 'Original'),
('Ter que comer um inseto vivo todo dia', 'Original'),
('nunca poder comer carne de novo', 'Original'),
('Só poder beber água morna pelo resto da vida', 'Original'),
('só poder comer comida sem tempero', 'Original'),
('Comer a mesma refeição favorita todo dia', 'Original'),
('poder comer qualquer coisa menos a sua favorita', 'Original'),
('Nunca mais poder usar redes sociais', 'Original'),
('nunca mais poder usar streaming', 'Original'),
('Perder todo o histórico de fotos do celular', 'Original'),
('perder todos os contatos salvos', 'Original'),
('Só poder usar o celular 30 minutos por dia', 'Original'),
('poder usar à vontade mas sem internet', 'Original'),
('Ter todas as suas mensagens tornadas públicas', 'Original'),
('perder acesso a todas as suas contas para sempre', 'Original'),
('Nunca mais poder ouvir música', 'Original'),
('nunca mais poder assistir a vídeos', 'Original'),
('Ganhar R.000 por mês em um trabalho que você odeia', 'Original'),
('R.000 em um trabalho que ama', 'Original'),
('Ser demitido injustamente sem poder se defender', 'Original'),
('ter que demitir seu melhor amigo', 'Original'),
('Trabalhar 80 horas por semana sem férias', 'Original'),
('trabalhar 20 horas ganhando só o suficiente para sobreviver', 'Original'),
('Perder todas as suas economias de uma vez', 'Original'),
('gastar 30% de tudo que ganhar com coisas inúteis para sempre', 'Original'),
('Ter todo o dinheiro do mundo mas nunca poder gastar nada', 'Original'),
('ter exatamente o suficiente mas gastar como quiser', 'Original'),
('Viajar para qualquer lugar do mundo sem poder escolher o destino', 'Original'),
('nunca viajar mas conhecer tudo pelos livros', 'Original'),
('Ficar preso em uma ilha deserta por um ano com uma pessoa que você odeia', 'Original'),
('em casa sozinho por dois anos', 'Original'),
('Perder a bagagem com documentos em viagem internacional', 'Original'),
('voltar de férias e descobrir que perdeu o emprego', 'Original'),
('Ter medo de avião e precisar viajar toda semana', 'Original'),
('ter medo de altura e morar no 30 andar', 'Original'),
('Viver em outro país sem falar o idioma', 'Original'),
('ficar no Brasil sem nunca poder sair', 'Original'),
('Chamar o professor de mãe na frente da turma', 'Original'),
('soltar um pum alto em uma reunião importante', 'Original'),
('Enviar uma mensagem íntima para o contato errado', 'Original'),
('receber uma mensagem íntima de alguém inesperado', 'Original'),
('Aparecer de pijama em uma formatura', 'Original'),
('ir a uma festa fantasiado sem precisar', 'Original'),
('Esquecer o nome de alguém que você vê todo dia', 'Original'),
('lembrar de todos os nomes mas sempre chamar pelo errado', 'Original'),
('Cair de cara no chão em público', 'Original'),
('gaguejar em um discurso importante ao vivo', 'Original'),
('Poder parar o tempo mas envelhecer normalmente na pausa', 'Original'),
('poder voltar no tempo mas não poder mudar nada', 'Original'),
('Ser rico mas sem amigos', 'Original'),
('ser pobre mas com os melhores amigos do mundo', 'Original'),
('Ter a força de um super-herói mas sem controle', 'Original'),
('ter a velocidade de um super-herói mas só no modo lento', 'Original'),
('Ser imortal e ver todos morrerem ao seu redor', 'Original'),
('ter uma vida curta mas repleta de felicidade', 'Original'),
('Saber tudo sobre ciência mas não entender nada de arte', 'Original'),
('entender tudo de arte mas não saber nada de ciência', 'Original'),
('Poder falar com animais mas todos te odiarem', 'Original'),
('não poder falar com animais mas todos te adorarem', 'Original'),
('Ser perseguido por uma galinha furiosa toda vez que sair de casa', 'Original'),
('ter que tocar em um caracol todo dia', 'Original'),
('Ter um leão manso com você que aterroriza os vizinhos', 'Original'),
('um cachorro que late 24 horas sem parar', 'Original'),
('Acordar uma vez por semana transformado em um animal aleatório', 'Original'),
('nunca mais poder ver animais', 'Original'),
('Ter que carregar um frango vivo na mochila para todo lugar', 'Original'),
('ter que viver com um peixe enorme na banheira', 'Original'),
('Saber todos os segredos da sua família', 'Original'),
('que sua família saiba todos os seus segredos', 'Original'),
('Que seus pais leiam todas as suas mensagens', 'Original'),
('que seu chefe saiba tudo que você faz nas horas vagas', 'Original'),
('Passar o Natal sozinho todo ano', 'Original'),
('passar todas as festas de aniversário com quem você não suporta', 'Original'),
('Decepcionar quem você mais ama uma vez para sempre', 'Original'),
('decepcionar um desconhecido toda semana', 'Original'),
('Perder contato com todos os amigos por um ano', 'Original'),
('ver seus amigos todo dia mas nunca ter uma conversa profunda', 'Original');
